- name: install openshift container storage
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: ensure project exists
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            labels:
              openshift.io/cluster-monitoring: "true"
            name: openshift-storage
          spec: {}

    - name: ensure operatorgroup exists
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: openshift-storage
            namespace: openshift-storage
          spec:
            targetNamespaces:
              - openshift-storage

    - name: ensure subscription exists
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: ocs-operator
            namespace: openshift-storage
          spec:
            channel: "{{ lookup('ini', 'container_storage section=operators file=/app/versions.ini') }}"
            name: ocs-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            installPlanApproval: "Automatic"
      register: op_subscribe

    - name: ensure storagecluster exists
      k8s:
        state: present
        definition: "{{ lookup('template', './ocs-storagecluster.yml.j2') | from_yaml }}"
      retries: 60
      delay: 15
      register: apply
      until: apply is success
