- name: install openshift container storage
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: ensure project exists
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            labels:
              openshift.io/cluster-monitoring: "true"
            name: openshift-storage
          spec: {}

    - name: ensure operatorgroup exists
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: openshift-storage
            namespace: openshift-storage
          spec:
            targetNamespaces:
              - openshift-storage

    - name: ensure subscription exists
      k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: ocs-operator
            namespace: openshift-storage
          spec:
            channel: "{{ lookup('ini', 'container_storage section=operators file=/app/versions.ini') }}"
            name: ocs-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            installPlanApproval: "Automatic"
      register: op_subscribe

    - name: ensure storagecluster exists
      k8s:
        state: present
        definition: "{{ lookup('template', './ocs-storagecluster.yml.j2') | from_yaml }}"
      retries: 60
      delay: 15
      register: apply
      until: apply is success

    - name: wait for storage class to be ready
      k8s_info:
        api_version: v1
        kind: StorageCluster
        name: ocs-storagecluster
        namespace: openshift-storage
        wait: yes
        wait_condition:
          type: Available

    - name: ensure rbd is the default storage class
      k8s:
        definition:
          apiVersion: v1
          kind: StorageClass
          metadata:
            name: ocs-storagecluster-ceph-rbd
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"

    - name: ensure registry storage exists
      k8s:
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: image-registry-storage
            namespace: openshift-image-registry
          spec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 100Gi
            volumeMode: Filesystem
            storageClassName: ocs-storagecluster-cephfs

    - name: ensure the registry is configured
      k8s:
        definition:
          apiVersion: imageregistry.operator.openshift.io/v1
          kind: Config
          metadata:
            name: cluster
          spec:
            managementState: Managed
            storage:
              pvc:
                claim: image-registry-storage

    - name: wait for the registry to become available
      k8s_info:
        api_version: imageregistry.operator.openshift.io/v1
        kind: Config
        name: cluster
        wait: yes
        wait_condition:
          type: "{{ item.type }}"
          status: "{{ item.status }}"
      loop:
        - type: Removed
          status: false
        - type: Available
          status: true
