- name: ensure working directory exists
  file:
    path: "{{ openshift_installer_dir }}"
    state: directory
    mode: 0700

- name: download openshift installer
  get_url:
    url: "{{ openshift_installer_source }}"
    dest: "{{ openshift_installer_dir }}/openshift-installer.tar.gz"
    mode: 0644
    unsafe_writes: yes
    validate_certs: "{{ openshift_installer_proxy_ca == '' }}"
  register: pkg_download

- name: extract openshift installer
  command: "tar xvzf '{{ openshift_installer_dir }}/openshift-installer.tar.gz' -C '{{ openshift_installer_dir }}'"
  args:
    warn: no
  when: pkg_download is changed

- name: create cluster install config
  template:
    src: install-config.yaml.j2
    dest: "{{ item }}"
  loop:
    - "{{ openshift_installer_dir }}/install-config.yaml"
    - "{{ openshift_installer_dir }}/install-config.yaml.bkp"

- name: cleanup previous install artifacts
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ openshift_installer_dir }}/.openshift_install_state.json"
    - "{{ openshift_installer_dir }}/.openshift_install.log"
    - "{{ openshift_installer_dir }}/metadata.json"
    - "{{ openshift_installer_dir }}/bootstrap.ign"
    - "{{ openshift_installer_dir }}/master.ign"
    - "{{ openshift_installer_dir }}/worker.ign"
    - "{{ openshift_installer_dir }}/auth"

- name: create installation manifests # noqa no-changed-when
  shell: >
    {{ openshift_installer_dir }}/openshift-install create manifests
    --dir={{ openshift_installer_dir }}

- name: create cache disk machine configs
  template:
    src: 98-cache-disk.yaml.j2
    dest: "{{ openshift_installer_dir }}/openshift/98-cache-disk.yaml"
  when: openshift_installer_cache_disk|length > 0

- name: create disk encryption machine configs
  template:
    src: "{{ item }}.j2"
    dest: "{{ openshift_installer_dir }}/openshift/{{ item }}"
  with_items:
    - 99-openshift-master-tang-encryption.yaml
    - 99-openshift-worker-tang-encryption.yaml

- name: create ignition files # noqa no-changed-when
  shell: >
    {{ openshift_installer_dir }}/openshift-install create ignition-configs
    --dir={{ openshift_installer_dir }}
