- name: apply firmware
  hosts: cluster,!virtual
  become: false
  gather_facts: false
  serial: 1

  vars_prompt:
    - name: username
      prompt: Current iLO Admin User [defaults to value in config]
      private: false
    - name: password
      prompt: Current iLO Admin Password [defaults to value in config]
      private: true

  tasks:
    - name: use default ilo user when requested
      set_fact:
        username: "{{ mgmt_user }}"
      when: username == ""

    - name: use default ilo password when requested
      set_fact:
        password: "{{ mgmt_password }}"
      when: password == ""

    - name: create tmp config file
      tempfile:
        state: file
      register: config
      delegate_to: localhost

    - name: login to ilo
      shell: ilorest -c "{{ config.path }}" login "{{ mgmt_hostname }}" -u '{{ username }}' -p '{{ password }}'
      changed_when: false
      delegate_to: localhost

    - name: ensure server is off
      include_role:
        name: management
        defaults_from: main.yml
        tasks_from: "poweroff/{{ mgmt_provider }}.yml"
        vars_from: "{{ mgmt_provider }}.yml"
        handlers_from: "{{ mgmt_provider }}.yml"
      vars:
        management_hostname: "{{ mgmt_hostname }}"
        management_user: "{{ username }}"
        management_pass: "{{ password }}"

    - import_tasks: iloaccount.yml

    - import_tasks: bios.yml

    - import_tasks: boot.yml

    - name: set bios setup for next boot to check clock
      shell: ilorest -c "{{ config.path }}" bootorder --onetimeboot=BiosSetup --commit
      delegate_to: localhost

    - name: ensure server is on
      include_role:
        name: management
        defaults_from: main.yml
        tasks_from: "poweron/{{ mgmt_provider }}.yml"
        vars_from: "{{ mgmt_provider }}.yml"
        handlers_from: "{{ mgmt_provider }}.yml"
      vars:
        management_hostname: "{{ mgmt_hostname }}"
        management_user: "{{ username }}"
        management_pass: "{{ password }}"

    - name: wait for time to be configured
      pause:
        prompt: |
          Your system is now booting into the BIOS configuration menu. Please
          ensure that the system clock is set to the correct time. The system
          clock setting is under:
          System Configuration > BIOS/Platform Configuration (RBSU) > Date and Time.

          The system's iLO address is: https://{{ mgmt_hostname }}

    - name: ensure server is off
      include_role:
        name: management
        defaults_from: main.yml
        tasks_from: "poweroff/{{ mgmt_provider }}.yml"
        vars_from: "{{ mgmt_provider }}.yml"
        handlers_from: "{{ mgmt_provider }}.yml"
      vars:
        management_hostname: "{{ mgmt_hostname }}"
        management_user: "{{ username }}"
        management_pass: "{{ password }}"

    - name: logout of ilo
      shell: ilorest -c "{{ config.path }}" logout
      changed_when: false
      delegate_to: localhost
