#!/bin/bash

HELP="""
USAGE: create COMMAND

Available Commands:
    all             Creates an OpenShift cluster.
    machines        Create any required virtual machines (like bootstrap).
    network         Deploys network dependencies for the cluster.
    load-balancer   Deploys the load balancer for the cluster.
    install-repos   Deploys the software/config source repos for install.
    cluster         Installs OpenShift onto the cluster nodes.
"""

## PARSE INPUTS
if [ $# -ne 1 ]; then
    echo "$HELP"
    exit 1
fi

## PREPARE ENVIRONMENT
cd /app
source /data/config.sh

## EXECUTE
case $1 in

    "machines")
        ansible-playbook /app/create_machines.yml || exit 1
        ;;

    "network")
        ansible-playbook /app/create_network.yml || exit 1
        ;;

    "load-balancer")
        ansible-playbook /app/create_loadbalancer.yml || exit 1
        ;;

    "install-repos")
        ansible-playbook /app/create_installrepos.yml || exit 1
        ;;

    "cluster")
        ansible-playbook /app/create_cluster.yml || exit 1
        ;;

    "all")
        ansible-playbook /app/create_all.yml || exit 1
        ;;

    *)
        echo "$HELP"
        exit 1
        ;;
esac
