#!/bin/bash

HELP="""
USAGE: create COMMAND

Available Commands:
    all             Creates an OpenShift cluster.
    network         Deploys network dependencies for the cluster.
    load-balancer   Deploys the load balancer for the cluster.
    machines        Create any required virtual machines (like bootstrap).
    install-repos   Deploys the software/config source repos for install.
    cluster         Installs OpenShift onto the cluster nodes.
"""
ALL_CMDS="network load-balancer machines install-repos cluster"

## PARSE INPUTS
if [ $# -ne 1 ]; then
    echo "$HELP"
    exit 1
fi
cmds=$1
if [ "$cmds" == "all" ]; then
    cmds="$ALL_CMDS"
fi

## PREPARE ENVIRONMENT
cd /app
source /data/config.sh

## EXECUTE
for cmd in $cmds; do
    case $cmd in

        "network")
            ansible-playbook /app/create_network.yml
            ;;

        "load-balancer")
            ansible-playbook /app/create_loadbalancer.yml
            ;;

        "machines")
            echo "m nyi"
            ;;

        "install-repos")
            ansible-playbook /app/create_installrepos.yml
            ;;

        "cluster")
            echo "c nyi"
            ;;

        *)
            echo "$HELP"
            exit 1
            ;;
    esac
done
