#!/bin/bash

export COOKBOOK=/app/deploy.d
CMDS=$(cd $COOKBOOK; ls -d * | awk '{ print "    " $1; }')
HELP="""
USAGE: deploy COMMAND [COMMAND_ARGS]

Available Commands:
    help
$CMDS
"""

## PARSE INPUTS
if [ $# -eq 0 ]; then
    echo "$HELP"
    exit 1
fi
if [ "$1" == "help" ]; then
    echo "$HELP"
    exit 0
fi
if ! echo "$CMDS" | grep "$1" &>/dev/null; then
    echo "$HELP"
    exit 1
fi

## PREPARE ENVIRONMENT
cd /app
source /data/config.sh
export KUBECONFIG=/data/openshift-installer/auth/kubeconfig

## EXECUTE
RECIPE=$1
shift
/bin/bash $COOKBOOK/$RECIPE/main.sh $@