- name: ensure cockpit plugin dir exists
  file:
    path: /usr/local/share/cockpit/faros
    state: directory
    mode: 0755
  notify: install cockpit plugin

- name: Flush handlers
  meta: flush_handlers

- name: add links to cockpit - insert
  lineinfile:
    path: /usr/local/share/cockpit/faros/index.html
    line: <li><a href="{{ item.url }}" target="_blank">{{ item.name }}</a></li> <!-- {{ item.icon }} -->
    # yamllint disable-line
    insertafter: <!-- ##START## -->
    regexp: "{{ item.name }}"
  loop: "{{ cockpit_links }}"
  when: cockpit_links_action == 'insert'

- name: add links to cockpit - append
  lineinfile:
    path: /usr/local/share/cockpit/faros/index.html
    line: <li><a href="{{ item.url }}" target="_blank">{{ item.name }}</a></li> <!-- {{ item.icon }} -->
    # yamllint disable-line
    insertbefore: <!-- ##END## -->
    regexp: "{{ item.name }}"
  loop: "{{ cockpit_links }}"
  when: cockpit_links_action == 'append'

- name: remove links from cockpit
  lineinfile:
    path: /usr/local/share/cockpit/faros/index.html
    line: <li><a href="{{ item.url }}" target="_blank">{{ item.name }}</a></li> <!-- {{ item.icon }} -->
    state: absent
    regexp: "{{ item.name }}"
  loop: "{{ cockpit_links }}"
  when: cockpit_links_action == 'delete'
