- name: Wait for management interfaces to respond
  hosts: cluster:!virtual
  become: no
  gather_facts: no

  tasks:
    - name: wait for mgmt interfaces reachable from bastion
      shell: ping -c 1 {{ mgmt_hostname }}
      delegate_to: "{{ groups.bastion_hosts[0] }}"
      become: no
      register: node_ping
      until: "node_ping is not failed"
      retries: 360
      delay: 10
      changed_when: no
