#!/usr/bin/env ansible-playbook

- name: Configure layer 3 routing and network services
  hosts: wan
  gather_facts: no
  become: yes

  roles:
    - name: router
      router_all_interfaces: "{{ all_interfaces }}"
      router_lan_interfaces: "{{ lan_interfaces }}"
      router_lan_address: "{{ hostvars.lan.ansible_host }}"
      router_subnet_mask: "{{ subnet_mask }}"
      router_wan_interface: "{{ wan_interface }}"
      router_loadbalancer: "{{ loadbalancer_vip }}"
    # - name: dhcp-server
    # - name: dns-server
    # - name: hardening # look the root account, etc
