#!/usr/bin/env ansible-playbook

- import_playbook: util_vm_facts.yml


- name: create red hat coreos ignition files
  hosts: localhost
  gather_facts: no
  become: no

  roles:
    - name: openshift-installer
      openshift_installer_dir: /data/openshift-installer
      openshift_installer_cluster_id: '{{ cluster_name }}'
      openshift_installer_base_domain: '{{ cluster_domain }}'
      openshift_installer_control_plane: '{{ groups.control_plane }}'
      openshift_installer_ssh_key: '{{ lookup("file", ansible_ssh_private_key_file + ".pub") }}'
      openshift_installer_pull_secret: '{{ pull_secret | to_json }}'


- name: create openshift installation source repositories
  hosts: bastion_hosts
  gather_facts: yes
  become: yes

  roles:
    - name: content-servers
    - name: rhcos-images
      rhcos_images_bootstrap_ign: /data/openshift-installer/bootstrap.ign
      rhcos_images_master_ign: /data/openshift-installer/master.ign
      rhcos_images_worker_ign: /data/openshift-installer/worker.ign

  post_tasks:
    - name: setup dhcp
      include_role:
        name: dhcp-nextserver
        defaults_from: "main.yml"
        handlers_from: "{{ hostvars.dhcp.provider }}.yml"
        tasks_from: "{{ hostvars.dhcp.provider }}.yml"
        vars_from: "{{ hostvars.dhcp.provider }}.yml"


- name: create pxelinux kickstart files
  hosts: cluster
  gather_facts: no

  roles:
    - name: pxelinux-kickstarts
      pxelinux_kickstarts_pxe_server: "{{ groups.bastion_hosts.0 }}"
      pxelinux_kickstarts_content_server: "http://{{ hostvars[groups.bastion_hosts.0].ansible_host }}:8081"
      pxelinux_kickstarts_host_role: "{{ node_role }}"
