- name: turn on uid light
  hosts: cluster
  become: false
  gather_facts: false

  tasks:
    - name: turn on uid light (ilo)
      raw: uid on
      changed_when: true
      delegate_to: "{{ inventory_hostname }}-mgmt"
      register: test
