#!/usr/bin/env ansible-playbook
- name: gather virtual machine facts from qemu-kvm
  hosts: virtual
  gather_facts: false
  become: false

  roles:
    - name: vm-gather-facts
      hypervisor: '{{ groups.bastion_hosts.0 }}'
      primary_network: faroslan
