- name: deploy kickstarts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - src: pxelinux.{{ pxelinux_kickstarts_profile }}.cfg.j2
      dest: "/var/lib/tftpboot/pxelinux.cfg/01-{{ mac_address | lower | regex_replace (':', '-') }}"
    - src: grub.{{ pxelinux_kickstarts_profile }}.cfg.j2
      dest: "/var/lib/tftpboot/uefi/grub.cfg-01-{{ mac_address | lower | regex_replace (':', '-') }}"
  delegate_to: "{{ pxelinux_kickstarts_pxe_server }}"
  become: yes
