- name: ensure masquerading is enabled
  firewalld:
    zone: "external"
    masquerade: 'yes'
    permanent: yes
    immediate: yes
    state: enabled

- name: configure ingress ssh to bastion
  firewalld:
    zone: external
    service: ssh
    permanent: yes
    immediate: yes
    state: '{% if "SSH to Bastion" in allowed_services %}enabled{% else %}disabled{% endif %}'

- name: configure ingress https to cockpit
  firewalld:
    zone: external
    service: cockpit
    permanent: yes
    immediate: yes
    state: '{% if "HTTPS to Cockpit Panel" in allowed_services %}enabled{% else %}disabled{% endif %}'

- name: configure ingress network routing
  firewalld:
    zone: external
    rich_rule: "rule family=ipv4 destination address={{ router_lan_subnet }} drop"
    permanent: yes
    immediate: yes
    state: '{% if "External to Internal Routing - DANGER" in allowed_services %}disabled{% else %}enabled{% endif %}'

- name: ensure internal masquerading is configured
  firewalld:
    zone: "internal"
    masquerade: '{% if "External to Internal Routing - DANGER" in allowed_services %}yes{% else %}no{% endif %}'
    permanent: yes
    immediate: yes
    state: enabled

- name: ensure https to cluster api is routed
  firewalld:
    zone: "external"
    port: 6443/tcp
    permanent: yes
    immediate: yes
    state: '{% if "HTTPS to Cluster API" in allowed_services and "External to Internal Routing - DANGER" in allowed_services %}enabled{% else %}disabled{% endif %}'

- name: ensure https to cluster apps is routed
  firewalld:
    zone: "external"
    port: 443/tcp
    permanent: yes
    immediate: yes
    state: '{% if "HTTPS to Cluster Apps" in allowed_services and "External to Internal Routing - DANGER" in allowed_services %}enabled{% else %}disabled{% endif %}'

- name: ensure http to cluster apps is routed
  firewalld:
    zone: "external"
    port: 80/tcp
    permanent: yes
    immediate: yes
    state: '{% if "HTTPS to Cluster Apps" in allowed_services and "External to Internal Routing - DANGER" in allowed_services %}enabled{% else %}disabled{% endif %}'

- include_tasks: manage_forward_ports.yaml
  loop:
    - name: ingress https to cluster api
      rule: port=6443:proto=tcp:toport=6443:toaddr={{ router_loadbalancer }}
      exist: '{{ "HTTPS to Cluster API" in allowed_services and "External to Internal Routing - DANGER" not in allowed_services }}'
    - name: ingress http to cluster apps
      rule: port=80:proto=tcp:toport=80:toaddr={{ router_loadbalancer }}
      exist: '{{ "HTTP to Cluster Apps" in allowed_services and "External to Internal Routing - DANGER" not in allowed_services }}'
    - name: ingress https to cluster apps
      rule: port=443:proto=tcp:toport=443:toaddr={{ router_loadbalancer }}
      exist: '{{ "HTTPS to Cluster Apps" in allowed_services and "External to Internal Routing - DANGER" not in allowed_services }}'
  loop_control:
    loop_var: "outer"
    label: "{{ outer.name }}"
