- name: get PAT status
  shell: 'firewall-cmd --zone=external --list-all | grep -c "{{ outer.rule }}"'
  register: rule_check
  changed_when: no
  ignore_errors: yes

- name: calculate PAT desired state
  set_fact:
    action: '{% if outer.exist %}add-forward-port{% else %}remove-forward-port{% endif %}'

- name: configure PAT
  command: "firewall-cmd --zone=external --{{ action }}={{ outer.rule }}"
  when: "rule_check is failed == outer.exist"
- name: configure PAT
  command: "firewall-cmd --zone=external --permanent --{{ action }}={{ outer.rule }}"
  when: "rule_check is failed == outer.exist"
