- name: Install tftp required packages
  yum:
    name: tftp-server, syslinux
    state: installed

- name: Ensure tftp is allowed on local network
  ansible.posix.firewalld:
    zone: internal
    service: tftp
    state: enabled
    permanent: true
    immediate: true

- name: Create TFTP directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /var/lib/tftpboot/pxelinux.cfg
    - /var/lib/tftpboot/uefi
  notify:
    - restart tftp

- name: Copy pxelinux.0
  shell: "cp -ra /usr/share/syslinux/* /var/lib/tftpboot/; chmod 644 /var/lib/tftpboot/pxelinux.0"
  args:
    creates: "/var/lib/tftpboot/pxelinux.0"

- name: Copy EFI boot programs
  copy:
    src: "{{ item }}"
    dest: "/var/lib/tftpboot/uefi/{{ item }}"
    mode: 0644
    owner: root
    group: root
    seuser: system_u
    serole: object_r
    setype: tftpdir_rw_t
    selevel: s0
  loop:
    - bootx64.efi
    - grubx64.efi

- name: Generate the default pxe config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - src: default.j2
      dest: /var/lib/tftpboot/pxelinux.cfg/default
    - src: grub.cfg.j2
      dest: /var/lib/tftpboot/uefi/grub.cfg
  notify:
    - restart tftp

- name: Verify selinux context on all TFTP files
  command: restorecon -Rv /var/lib/tftpboot/
  register: restorecon
  changed_when: restorecon.stdout | length > 0

- name: Starting PXE services
  service:
    name: tftp.socket
    enabled: true
    state: started
