- name: restart dhcpd service
  service:
    name: dhcpd
    state: restarted
  listen: restart dhcpd
  delegate_to: dhcp
  become: true

- name: sleep
  command: sleep 2
  delegate_to: localhost
  become: false
  listen: restart dhcpd
