#!/usr/bin/env ansible-playbook
- name: Uninstall cluster load balancer
  hosts: bastion
  gather_facts: false
  become: true

  tasks:
    - name: shutdown the load balancer service
      systemd:
        name: haproxy
        state: stopped
        enabled: false
        force: true

    - name: shutdown the VIP service
      systemd:
        name: keepalived
        state: stopped
        enabled: false
        force: true

    - name: delete load balancer configuration
      file:
        path: /etc/haproxy/haproxy.cfg
        state: absent

    - name: delete the vip configuration
      file:
        path: /etc/keepalived/keepalived.conf
        state: absent

    - name: remove vip cached password
      file:
        path: /data/keepalived.pass
        state: absent
      delegate_to: localhost
