- name: wipe local storage
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: wipe drives per host
      include_tasks: wipe-host.yml
      loop: "{{ stg_drives }}"
      loop_control:
        loop_var: outer
