- name: gather existing virtual machines
  virt:
    command: list_vms
  register: all_vms
  delegate_to: "{{ virtual_machine_hypervisor }}"
  become: true

- name: create virtual machine
  shell: >
    virt-install --name={{ virtual_machine_name }}
    --vcpus={{ virtual_machine_vcpus }}
    --memory={{ virtual_machine_memory }}
    --disk={{ virtual_machine_disk }}
    --network={{ virtual_machine_network }}
    --boot {{ virtual_machine_boot }}
    --graphics {{ virtual_machine_graphics }}
    --os-variant {{ virtual_machine_os_variant }}
    --cpu Haswell-noTSX
    --noautoconsole
    --check disk_size=off
    {% if virtual_machine_autostart %}--autostart{% endif %}
  when: virtual_machine_name not in all_vms.list_vms
  delegate_to: "{{ virtual_machine_hypervisor }}"
  become: true
  # Haswell CPU specification fixes some bug in kvm where it might not like
  # the EL8000 CPUs. Or something. I don't know, I'm tired and it works.
  # https://bugzilla.redhat.com/show_bug.cgi?id=1657738

- name: ensure host devices are mapped
  include_tasks: host_devices.yml
  loop: '{{ virtual_machine_hostdevs }}'
  loop_control:
    loop_var: device

- name: ensure host drives are mapped
  include_tasks: host_drives.yml
  loop: '{{ virtual_machine_hostdrives }}'
  loop_control:
    loop_var: drive
